-- Cria as tabelas na ordem correta de dependência

CREATE TABLE profissoes (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE clientes (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cpf VARCHAR(11) UNIQUE NOT NULL,
    rg VARCHAR(9) UNIQUE NOT NULL,
    nome VARCHAR(150) NOT NULL,
    data_nascimento DATE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    salario DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    vl_patrimonio DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    id_profissao INT NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    CONSTRAINT fk_cliente_profissao FOREIGN KEY (id_profissao) REFERENCES profissoes(id)
);

CREATE TABLE telefones (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    numero VARCHAR(15) NOT NULL,
    tipo VARCHAR(15) NOT NULL,
    id_cliente INT NOT NULL,
    CONSTRAINT fk_telefone_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id),
    CONSTRAINT ck_tipo_telefone CHECK(tipo IN('residencial', 'celular'))
);

CREATE TABLE enderecos (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rua VARCHAR(255) NOT NULL,
    numero VARCHAR(20) NOT NULL,
    bairro VARCHAR(100) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    estado CHAR(2) NOT NULL, -- Ex: 'SP', 'RJ'
    cep VARCHAR(8) NOT NULL,
    complemento VARCHAR(100),
    id_cliente INT NOT NULL,
    CONSTRAINT fk_endereco_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id)
);

CREATE TABLE contas (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    agencia VARCHAR(4) NOT NULL,
    numero_conta VARCHAR(20) UNIQUE NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    saldo DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    data_hora_abertura TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_hora_fechamento TIMESTAMP, -- Fica nulo se estiver aberta
    estado VARCHAR(20) NOT NULL,
    id_cliente INT NOT NULL,
    CONSTRAINT fk_conta_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id),
    CONSTRAINT ck_estado_conta CHECK(estado IN('ativa', 'bloqueada', 'encerrada'))
);

CREATE TABLE chaves_pix (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    chave VARCHAR(100) UNIQUE NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    id_conta INT NOT NULL,
    CONSTRAINT fk_chave_pix_conta FOREIGN KEY (id_conta) REFERENCES contas(id),
    CONSTRAINT ck_tipo_chave_pix CHECK(tipo IN('email', 'telefone', 'aleatoria', 'cpf'))
);

-- Tabela ÚNICA para todas as transações
CREATE TABLE movimentacoes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    valor DECIMAL(15, 2) NOT NULL,
    data_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tipo VARCHAR(20) NOT NULL, -- 'PIX', 'TED', 'DEPOSITO', 'SAQUE'
    id_conta INT NOT NULL,
    
    -- Campos específicos para PIX (ficam NULL se for TED)
    chave_destino VARCHAR(100),

    -- Campos específicos para TED (ficam NULL se for PIX)
    num_conta_destino VARCHAR(20),
    agencia_destino VARCHAR(20),
    tipo_conta_destino VARCHAR(20),
    instituicao_destino VARCHAR(100),
    nome_destino VARCHAR(150),
    cpf_cnpj_destino VARCHAR(14),

    CONSTRAINT fk_movimentacao_conta FOREIGN KEY (id_conta) REFERENCES contas(id),
    CONSTRAINT ck_tipo_movimentacao CHECK(tipo IN('PIX', 'TED', 'DEPOSITO', 'SAQUE'))
);